### ISSUE TITLE
Merge checks

### ISSUE THREAD

**Issue by IanTapply22** [Simbotics/Simbot-Base#25]
Simply check if the description of a pull request contains something along the lines of "DO_NOT_MERGE" and don't allow the PR to merge. 

Something along the lines of the following should meet the criteria for this task:

```
name: Merge Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR description
        run: |
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')

          if [[ $PR_DESCRIPTION == *"DO_NOT_MERGE"* ]]; then
            echo "DO_NOT_MERGE found in the PR description. Merge not allowed."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
